import "./globals.css";
import Navbar from "@/Components/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="homepage">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
